version: 2

models:
  - name: int_order_item
    description: "This model contains full information about every order."
    columns:
      - name: order_id
        description: "Unique identifier for each order"
      - name: order_status
        description: "Status of order"
      - name: order_date
        description: "Date when order was placed" 
      - name: required_date
        description: "Date when order should be shipped" 
      - name: shipped_date
        description: "Actual date when order was shipped"
      - name: product_id
        description: "Unique identifier for each product"
      - name: product_name
        description: "Name of the product" 
      - name: brand_name
        description: "Name of the brand of the product" 
      - name: quantity
        description: "Number of products in order"
      - name: final_order_item_price
        description: "Final price of products in order, after discount" 
      - name: client_full_name
        description: "Name of the client placed the order"   
      - name: staff_full_name
        description: "Name of the staff processed the order"
      - name: staff_is_active
        description: "Indicator if the staff person is still working"  
      - name: store_id
        description: "Unique identifier for each store"
      - name: store_name
        description: "Name of the store"
