version: 2

models:
  - name: stg_brands
    description: "This model contains information about bike brands."
    columns:
      - name: brand_id
        description: "Primary key, unique identifier of each brand."
        tests:
            - unique
            - not_null

  - name: stg_categories
    description: "This model contains information about bike categories."
    columns:
      - name: category_id
        description: "Primary key, unique identifier of each bike category."
        tests:
            - unique
            - not_null

  - name: stg_customers
    description: "This model contains information about customers of Local Bike, including where they live ."
    columns:
      - name: customer_id
        description: "Primary key, unique identifier of each customer."
        tests:
            - unique
            - not_null

  - name: stg_sales_database__order_items
    description: "This model contains information about each item included in an order, including its price and discount."
    columns:
      - name: order_item_id
        description: "Primary key, unique identifier for each order item. Generated by concatenating order_id and product_id."
        tests:
            - unique
            - not_null
      - name: order_id
        description: "Foreign key linking the order item to the corresponding order."
        tests:
          - relationships:
              name: order_id_foreign_key_in_stg_order_items
              to: ref('stg_orders')
              field: order_id
      - name: product_id
        description: "Foreign key linking the order item to the corresponding product."
        tests:
          - relationships:
              name: product_id_foreign_key_in_stg_order_items
              to: ref('stg_products')
              field: product_id
      - name: final_order_item_price
        description: "The total amount for this order item, calculated as quantity * list_price * (1 - discount)."

  - name: stg_orders
    description: "This model contains information about orders placed by users, including the status of each order."
    columns:
      - name: order_id
        description: "Primary key, unique identifier for each order."
        tests:
            - unique
            - not_null
      - name: customer_id
        description: "Foreign key linking the order to the customer who made it."
        tests:
          - relationships:
              name: customer_id_foreign_key_in_stg_orders
              to: ref('stg_customers')
              field: customer_id
      - name: store_id
        description: "Foreign key linking the order to the store where the sale happened."
        tests:
          - relationships:
              name: store_id_foreign_key_in_stg_orders
              to: ref('stg_stores')
              field: store_id
      - name: staff_id
        description: "Foreign key linking the order to the staff member who made the sale happened."
        tests:
          - relationships:
              name: staff_id_foreign_key_in_stg_orders
              to: ref('stg_staffs')
              field: staff_id

  - name: stg_products
    description: "This model contains details of products available for sale, including price."
    columns:
      - name: product_id
        description: "Primary key, unique identifier for each product."
        tests:
            - unique
            - not_null
      - name: brand_id
        description: "Foreign key linking the product to it's brand."
        tests:
          - relationships:
              name: brand_id_foreign_key_in_stg_products
              to: ref('stg_brands')
              field: brand_id
      - name: category_id
        description: "Foreign key linking the product to it's category."
        tests:
          - relationships:
              name: category_id_foreign_key_in_stg_products
              to: ref('stg_categories')
              field: category_id

  - name: stg_staffs
    description: "This model contains information about shop staff."
    columns:
      - name: staff_id
        description: "Primary key, unique identifier for each product."
        tests:
            - unique
            - not_null

  - name: stg_stocks
    description: "This model contains information about the products left in the shop at the moment."
    columns:
      - name: stock_id
        description: "Primary key, unique identifier for each stock. Generated by concatenating store_id and product_id ."
        tests:
            - unique
            - not_null
      - name: store_id
        description: "Foreign key linking the stock to the store."
        tests:
          - relationships:
              name: store_id_foreign_key_in_stg_stocks
              to: ref('stg_stores')
              field: store_id
      - name: product_id
        description: "Foreign key linking the stock to the product."
        tests:
          - relationships:
              name: product_id_foreign_key_in_stg_stocks
              to: ref('stg_products')
              field: product_id

  - name: stg_stores
    description: "This model contains information about stores."
    columns:
      - name: store_id
        description: "Primary key, unique identifier for each store."
        tests:
            - unique
            - not_null
